version: '3.7'

services:
  apivendas-db:
    image: postgres
    container_name: apivendas-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apivendas
    volumes:
      - pgdata:/data/postgres

  apivendas-app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-app
    ports:
      - 3333:3333
    volumes:
      - .:/home/app
    depends_on:
      - apivendas-db
      - apivendas-redis

  apivendas-redis:
    image: 'bitnami/redis'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  apivendas-pgadmin:
    image: dpage/pgadmin4
    container_name: apivendas-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8000:80
    depends_on:
      - apivendas-db

volumes:
  pgdata:
    driver: local
